channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - librosa
  - tqdm
  - requests
  - colorama
  - ansiwrap
  - pyyaml
  - dataclassy
  - kaldi
  - sox
  - ffmpeg
  - pynini
  - openfst
  - baumwelch
  - ngram
  - praatio
  - biopython
  - sqlalchemy>=1.4
