channels:
  - conda-forge
  - pytorch
  - nvidia
  - anaconda
dependencies:
  - python>=3.8
  - numpy
  - librosa
  - pysoundfile
  - tqdm
  - requests
  - pyyaml
  - dataclassy
  - kaldi=*=*cpu*
  - scipy
  - pynini
  - openfst=1.8.3
  - scikit-learn
  - hdbscan
  - baumwelch
  - ngram
  - praatio=6.0.0
  - biopython
  - sqlalchemy>=2.0
  - pgvector
  - pgvector-python
  - sqlite
  - postgresql
  - psycopg2
  - click
  - setuptools_scm
  - pytest
  - pytest-mypy
  - pytest-cov
  - pytest-timeout
  - mock
  - coverage
  - coveralls
  - interrogate
  - kneed
  - matplotlib
  - seaborn
  - pip
  - rich
  - rich-click
  - kalpy
    # Tokenization dependencies
  - spacy
  - sudachipy
  - sudachidict-core
  - spacy-pkuseg
  - pip:
      - build
      - twine
      # Tokenization dependencies
      - python-mecab-ko
      - jamo
      - pythainlp
      - hanziconv
      - dragonmapper
