name: montreal-forced-aligner
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - librosa
  - tqdm
  - requests
  - colorama
  - pyyaml
  - kaldi
  - sox
  - pip
  - pip:
    - praatio>=5.0
