channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - librosa
  - tqdm
  - requests
  - colorama
  - ansiwrap
  - pyyaml
  - dataclassy
  - kaldi=*=*cpu*
  - sox
  - ffmpeg
  - pynini
  - openfst
  - hdbscan
  - baumwelch
  - ngram
  - praatio
  - biopython=1.79
  - sqlalchemy>=2.0
  - pgvector
  - pgvector-python
  - postgresql
  - psycopg2
  - click
  - pytorch
  - torchaudio
  - setuptools_scm
  - pytest
  - pytest-mypy
  - mock
  - coverage
  - coveralls
  - interrogate
  - numba
  - kneed
  - matplotlib
  - seaborn
  - pip:
      - build
      - twine
      - speechbrain
