channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy<2.1.0
  - librosa
  - pysoundfile
  - tqdm
  - requests
  - pyyaml
  - dataclassy
  - kaldi=*=*cpu*
  - scipy
  - pynini
  - openfst
  - scikit-learn
  - hdbscan
  - baumwelch
  - ngram
  - praatio>=6.0.0
  - sqlalchemy>=2.0
  - pgvector
  - pgvector-python
  - sqlite
  - postgresql
  - psycopg2
  - click
  - setuptools_scm
  - pytest
  - pytest-mypy
  - pytest-cov
  - pytest-timeout
  - mock
  - coverage
  - coveralls
  - interrogate
  - kneed
  - matplotlib
  - seaborn
  - rich
  - rich-click
  - kalpy>=0.8
  - pip
  - huggingface_hub
  - spacy
  - sudachipy
  - sudachidict-core
  - jamo
  - pythainlp
  - python-build
  - twine
  # speechbrain dependencies
  - transformers>=4.48.0
  - pandas<2.3.0
  - sentencepiece
  - pytorch=2.8.0
  - torchaudio=2.8.0
  # whisperx dependencies
  - triton
  - nltk
  - av<16.0.0
  - onnxruntime<1.20.0
  - pip:
      - speechbrain
      - whisperx
      # Tokenization dependencies
      - python-mecab-ko
      - hanziconv
      - dragonmapper
