channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - librosa
  - tqdm
  - requests
  - pyyaml
  - praatio=6.0.0
  - dataclassy
  - sqlalchemy>=2.0
  - pynini
  - pgvector
  - pgvector-python
  - postgresql
  - scikit-learn
  - hdbscan
  - psycopg2
  - biopython
  - click
  - setuptools_scm
  - importlib_metadata
  - sphinx
  - numpydoc
  - sphinx-design
  - sphinx-click
  - sphinx-intl
  - pydata-sphinx-theme
  - myst-parser
  - mock
  - setuptools-scm
  - kneed
  - matplotlib
  - seaborn
  - rich
  - rich-click
  - kaldi =*=cpu*
  - kalpy
