name: mfa
channels:
  - conda-forge
dependencies:
  - python>=3.8   # or 2.7 if you are feeling nostalgic
  - numpy
  - librosa
  - tqdm
  - requests
  - colorama
  - pyyaml
  - pip
  - interrogate
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - pip:
      - praatio >= 5.0
      - sphinxemoji
