channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - librosa
  - tqdm
  - requests
  - colorama
  - ansiwrap
  - pyyaml
  - praatio
  - dataclassy
  - sqlalchemy>=1.4
  - pip
  - biopython
  - pip:
      - sphinxemoji
      - sphinxcontrib-autoprogram
      - pydata-sphinx-theme
      - sphinx-design
      - interrogate
      - sphinx
      - numpydoc
      - importlib_metadata > 3.1
