channels:
  - conda-forge
  - pytorch
  - nvidia
  - anaconda
dependencies:
  - python>=3.11
  - numpy
  - librosa
  - tqdm
  - requests
  - pyyaml
  - dataclassy
  - kaldi=*=*cpu*
  - pynini
  - openfst=1.8.3
  - scikit-learn
  - hdbscan
  - baumwelch
  - ngram
  - praatio=6.0.0
  - biopython
  - sqlalchemy>=2.0
  - git
  - pgvector
  - pgvector-python
  - postgresql
  - psycopg2
  - click
  - pytorch
  - torchaudio
  - setuptools_scm
  - kneed
  - matplotlib
  - seaborn
  - sqlite
  - rich
  - rich-click
  - kalpy
  - spacy
  - sudachipy
  - sudachidict-core
  - spacy-pkuseg
  - pip
  - pip:
      - speechbrain
      - python-mecab-ko
      - jamo
      - pythainlp
      - dragonmapper
